services:
  db:
    image: postgres:14
    container_name: ideahive-db
    environment:
      POSTGRES_DB: ideahive_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - ideahive_data:/var/lib/postgresql/data
    restart: unless-stopped

  frontend:
    image: node:14
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000" # React dev server
    command: npm start

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://dev_user:dev_password@db:5432/ideahive_dev?sslmode=disable

volumes:
  ideahive_data:
    name: ideahive_data
